### ISSUE TITLE
Allow multi-line format in string values for generated yaml-files

### ISSUE THREAD

**Issue by blackhatcrazy** [SAP/configuration-tools-for-gitops#33]
Description:
Currently multi-line string values that are processed by the `coco generate` command will be collapsed into a single-line representation using `\n` characters instead. This may lead to very unwieldy generated yaml files.

ACTION ITEMS: (yamlfile package):
- maintain the format of the original yaml file for string values
- for merging 2 yaml files (`from` and `into`) persist the format of the `into` file per default
- add an optional CLI parameter `--user-from-format` to the `generate` command that allows to alter the persistent format from the `into` file to the `from` file

**Comment by Christopher257** [comment]
This behaviour is caused by whitespaces in either the template file or the manual input before a line break. 
Examples, where "_" marks the troubling whitespace: 
This yaml would be changed to a single line:
test:_
  - testvalue1
  - testvalue2
 
Whereas this yaml would work properly:
test:
  - testvalue1
  - testvalue2

**Comment by Christopher257** [comment]
This behaviour is caused by a whitespace before a line break either in the template file or the manual input.
Some examples, where `<WHITESPACE>` marks the troubling whitespace:
This yaml will be collapsed into a single line:
```
test:<WHITESPACE>
  - testvalue1
  - testvalue1
```
  
Whereas this yaml would not be collapsed:
```
test:
  - testvalue1
  - testvalue2
```

**Comment by blackhatcrazy** [comment]
non-issue (see comment by @Christopher257 )
