### ISSUE TITLE
define environments via the coco.yaml file

### ISSUE THREAD

**Issue by blackhatcrazy** [SAP/configuration-tools-for-gitops#34]
Current situation:
Environments for which file-generation happens are identified by yaml-files in the `values/` folder. This implicit identification logic does not lend itself for generalizations (like adding multiple value files for 1 environment).

ACTION ITEMS:

- Introduce new keys to the `coco.yaml` file that define an environment:
```yaml
type: (string) # options: [environment, component] identifies the the type of configuration.
values: (list of string) # Ordered list of relative file paths to value yaml files that will be used for file-generation. The value files will be merged from last to first (where later values overwrite overwrite earlier ones for same keys)
```
- Generalise the `generate` command to take the type field in `coco.yaml` files into account

**Comment by Christopher257** [comment]
Feature implemented and new release created #41
